meta_product_name: "Summer School By SHSG"
meta_title: "Boost your understanding of Technology"
meta_image: "favicon-32x32.png"
meta_description: "The Summer School organized by the student union teaches students about the latest trends in technology."
